# Gelin Eguinosa Rosique
# 2022


wrong_acronyms = {
    'ABSTRACT': 'abstract',
    'BACKGROUND': 'background',
    'CONCLUSION': 'conclusion',
    'CONCLUSIONS': 'conclusion',
    'DESIGN': 'design',
    'ELECTRONIC': 'electronic',
    'ELECTRONICS': 'electronic',
    'FINDING': 'finding',
    'FINDINGS': 'finding',
    'HYPOTHESIS': 'hypothesis',
    'INTRODUCTION': 'introduction',
    'MATERIAL': 'material',
    'MATERIALS': 'material',
    'METHOD': 'method',
    'METHODS': 'method',
    'NUMBER': 'number',
    'NUMBERS': 'number',
    'OBJECTIVE': 'objective',
    'PARTICIPANT': 'participant',
    'PARTICIPANTS': 'participant',
    'PURPOSE': 'purpose',
    'RECENT': 'recent',
    'REGISTRATION': 'registration',
    'REGISTRATIONS': 'registration',
    'REVIEW': 'review',
    'REVIEWS': 'review',
    'RESPIRATORY': 'respiratory',
    'RESULT': 'result',
    'RESULTS': 'result',
    'SUMMARY': 'summary',
    'SUMMARIES': 'summary',
    'SUPPLEMENTARY': 'supplementary',
    'TRIAL': 'trial',
    'TRIALS': 'trial',
}
